import { MineSite, ChecklistItem, InspectionRecord, CAPAAction, StatutoryDocument } from '../types';

export const MOCK_MINES: MineSite[] = [
  {
    id: 'mine-kusmunda',
    name: 'Kusmunda OCP',
    subsidiary: 'SECL (Coal India)',
    location: 'Korba, Chhattisgarh',
    coordinates: [22.3524, 82.6854],
    riskScore: 78,
    riskCategory: 'HIGH',
    activeViolations: 4,
    openCapaCount: 3,
    lastInspectionDate: 'Today, 07:45 AM',
  },
  {
    id: 'mine-gevra',
    name: 'Gevra Mega Pit',
    subsidiary: 'SECL (Coal India)',
    location: 'Korba, Chhattisgarh',
    coordinates: [22.3411, 82.5932],
    riskScore: 42,
    riskCategory: 'MEDIUM',
    activeViolations: 2,
    openCapaCount: 1,
    lastInspectionDate: 'Yesterday',
  },
  {
    id: 'mine-dipka',
    name: 'Dipka Expansion OCP',
    subsidiary: 'SECL (Coal India)',
    location: 'Korba, Chhattisgarh',
    coordinates: [22.3188, 82.5539],
    riskScore: 24,
    riskCategory: 'LOW',
    activeViolations: 0,
    openCapaCount: 0,
    lastInspectionDate: '26 Sep 2026',
  },
  {
    id: 'mine-singrauli',
    name: 'Jayant Open Cast',
    subsidiary: 'NCL (Singrauli)',
    location: 'Singrauli, MP',
    coordinates: [24.1167, 82.6333],
    riskScore: 89,
    riskCategory: 'CRITICAL',
    activeViolations: 7,
    openCapaCount: 5,
    lastInspectionDate: '25 Sep 2026',
  },
];

export const INITIAL_CHECKLIST_TEMPLATES: ChecklistItem[] = [
  {
    id: 'chk-1',
    category: 'HAUL_ROAD',
    title: 'Haul Road Berm Height & Width',
    statutoryRule: 'DGMS (Tech) Circular No. 05/2010',
    description: 'Berm height must not be less than the diameter of the tyre of the largest vehicle (dumper) plying on the road.',
    status: 'NA',
    severityIfFailed: 'HIGH',
  },
  {
    id: 'chk-2',
    category: 'SLOPE_STABILITY',
    title: 'Bench Slope & Highwall Cracks',
    statutoryRule: 'Reg. 106 Coal Mines Regulations (CMR) 2017',
    description: 'Inspect top edge and toe of open-cast highwall for tension cracks, water seepage, or overhangs.',
    status: 'NA',
    severityIfFailed: 'CRITICAL',
  },
  {
    id: 'chk-3',
    category: 'DUST_SUPPRESSION',
    title: 'Haul Road Water Sprinklers & Fog Cannons',
    statutoryRule: 'Environment (Protection) Act & DGMS Guidelines',
    description: 'Continuous water spraying active on active transport corridors; mist cannons operating at transfer points.',
    status: 'NA',
    severityIfFailed: 'MEDIUM',
  },
  {
    id: 'chk-4',
    category: 'MACHINERY_HEMM',
    title: 'HEMM Pre-Shift Brake & Horn Check',
    statutoryRule: 'DGMS Safety Circular No. 09/2008',
    description: 'Audio-visual alarm, rear-view camera, emergency steering, and fail-safe service brakes operational on dumpers and excavators.',
    status: 'NA',
    severityIfFailed: 'HIGH',
  },
  {
    id: 'chk-5',
    category: 'PPE_WORKER_SAFETY',
    title: 'Contractor Labor PPE & Safety Induction',
    statutoryRule: 'Mines Vocational Training Rules 1966',
    description: 'All contractor personnel wearing DGMS-certified hard helmets, fluorescent high-vis jackets, and steel-toe boots.',
    status: 'NA',
    severityIfFailed: 'HIGH',
  },
];

export const SEED_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'INSP-2026-0928-01',
    mineId: 'mine-kusmunda',
    mineName: 'Kusmunda OCP',
    zone: 'Pit 4 - North Haul Road',
    inspectorId: 'FO-9412',
    inspectorName: 'Rajeshwar Sharma',
    timestamp: '2026-09-28T07:45:00.000Z',
    totalChecks: 5,
    passedChecks: 3,
    failedChecks: 2,
    criticalIssuesFound: 1,
    status: 'SYNCED',
    syncedAt: '2026-09-28T08:15:00.000Z',
    overallComments: 'High dust suspension near Ramp 3 due to dry surface. Haul road berm eroded on curve #2.',
    items: [
      {
        id: 'chk-1',
        category: 'HAUL_ROAD',
        title: 'Haul Road Berm Height & Width',
        statutoryRule: 'DGMS (Tech) Circular No. 05/2010',
        description: 'Berm height must not be less than the diameter of the tyre of the largest vehicle.',
        status: 'FAIL',
        severityIfFailed: 'HIGH',
        observationNotes: 'Berm collapsed over 40m stretch near Ramp 3 turn. Dumper spill hazard detected.',
      },
      {
        id: 'chk-2',
        category: 'SLOPE_STABILITY',
        title: 'Bench Slope & Highwall Cracks',
        statutoryRule: 'Reg. 106 CMR 2017',
        description: 'Inspect top edge and toe of open-cast highwall for tension cracks.',
        status: 'FAIL',
        severityIfFailed: 'CRITICAL',
        observationNotes: 'Micro-fissures observed on Bench 14 upper terrace after monsoon rain.',
      },
      {
        id: 'chk-3',
        category: 'DUST_SUPPRESSION',
        title: 'Haul Road Water Sprinklers & Fog Cannons',
        statutoryRule: 'Environment (Protection) Act',
        description: 'Continuous water spraying active on transport corridors.',
        status: 'PASS',
        severityIfFailed: 'MEDIUM',
      },
      {
        id: 'chk-4',
        category: 'MACHINERY_HEMM',
        title: 'HEMM Pre-Shift Brake & Horn Check',
        statutoryRule: 'DGMS Circular No. 09/2008',
        description: 'Audio-visual alarm and emergency steering operational.',
        status: 'PASS',
        severityIfFailed: 'HIGH',
      },
      {
        id: 'chk-5',
        category: 'PPE_WORKER_SAFETY',
        title: 'Contractor Labor PPE & Safety Induction',
        statutoryRule: 'Mines Vocational Training Rules 1966',
        description: 'All contractor personnel wearing certified PPE.',
        status: 'PASS',
        severityIfFailed: 'HIGH',
      },
    ],
  },
];

export const SEED_CAPA_ACTIONS: CAPAAction[] = [
  {
    id: 'CAPA-8821',
    inspectionId: 'INSP-2026-0928-01',
    mineId: 'mine-kusmunda',
    zone: 'Pit 4 - North Haul Road Ramp 3',
    title: 'Rebuild Collapsed Haul Road Berm (40m)',
    description: 'Rebuild compacted earth/rock berm to at least 2.2m height (exceeding 240T Cat 793 dumper tyre diameter) with reflector posts.',
    violationType: 'HAUL_ROAD_NON_COMPLIANCE',
    severity: 'HIGH',
    assignedTo: 'M/s Dilip Buildcon (Contractor Supervisor)',
    dueDate: '2026-09-29T18:00:00.000Z',
    status: 'OPEN',
    createdAt: '2026-09-28T08:15:00.000Z',
  },
  {
    id: 'CAPA-8822',
    inspectionId: 'INSP-2026-0928-01',
    mineId: 'mine-kusmunda',
    zone: 'Bench 14 - Upper Highwall',
    title: 'Slope Radar Sensor & Crack Gauge Installation',
    description: 'Install tell-tale crack gauges and restrict heavy machine movement within 30m of Highwall Bench 14 until geotechnical clearance.',
    violationType: 'SLOPE_INSTABILITY_RISK',
    severity: 'CRITICAL',
    assignedTo: 'Sr. Geotechnical Officer (SECL)',
    dueDate: '2026-09-28T20:00:00.000Z',
    status: 'IN_PROGRESS',
    createdAt: '2026-09-28T08:15:00.000Z',
  },
  {
    id: 'CAPA-8790',
    inspectionId: 'INSP-2026-0925-04',
    mineId: 'mine-kusmunda',
    zone: 'Muster Point #2',
    title: 'Replace Defective Audio-Visual Alarm on Dumper D-409',
    description: 'Reverse alarm was inaudible beyond 5 meters. Mandate DGMS-approved 112dB smart reversing chime.',
    violationType: 'MACHINERY_SAFETY',
    severity: 'HIGH',
    assignedTo: 'HEMM Maintenance Workshop',
    dueDate: '2026-09-27T12:00:00.000Z',
    status: 'PENDING_VERIFICATION',
    closureNotes: 'Replaced alarm horn unit and tested with decibel meter. Sound level measured 114 dB at 10m.',
    createdAt: '2026-09-25T14:30:00.000Z',
  },
];

export const SEED_STATUTORY_DOCS: StatutoryDocument[] = [
  {
    id: 'DOC-DGMS-01',
    mineId: 'mine-kusmunda',
    contractorName: 'Eastern Coal Logistics Ltd',
    documentType: 'HEMM_FITNESS',
    documentNumber: 'DGMS/CZ/KUS/FIT-2026-894',
    issuingAuthority: 'DGMS Central Zone Bilaspur',
    issueDate: '2025-10-15',
    expiryDate: '2026-10-14',
    status: 'EXPIRING_SOON',
    ocrConfidence: 96,
    extractedFields: {
      vehicleNumber: 'CG-12-BG-4901',
      model: 'Komatsu HD785-7',
      fitnessGrade: 'Grade-A Heavy Mining',
      nextInspectionDue: '14 Oct 2026',
    },
  },
  {
    id: 'DOC-ENV-02',
    mineId: 'mine-kusmunda',
    documentType: 'ENVIRONMENTAL_CLEARANCE',
    documentNumber: 'MoEFCC/EC/MIN/2019/331',
    issuingAuthority: 'Ministry of Environment, Forest & Climate Change',
    issueDate: '2020-04-01',
    expiryDate: '2030-03-31',
    status: 'VALID',
    ocrConfidence: 99,
    extractedFields: {
      approvedCapacity: '50 MTPA (Million Tonnes Per Annum)',
      clearanceCondition: 'Zero liquid discharge + continuous AAQMS monitoring',
    },
  },
  {
    id: 'DOC-LABOR-03',
    mineId: 'mine-kusmunda',
    contractorName: 'Pragati Infra Earthmovers',
    documentType: 'CONTRACTOR_LABOR_LICENSE',
    documentNumber: 'CLC/CG/KRB/CON-4401',
    issuingAuthority: 'Office of Chief Labour Commissioner (Central)',
    issueDate: '2025-09-01',
    expiryDate: '2026-09-20',
    status: 'EXPIRED',
    ocrConfidence: 94,
    extractedFields: {
      maxAuthorizedWorkers: '180 Personnel',
      statutoryPFRegistration: 'CG-BIL-008472-A',
      currentStatus: 'EXPIRED 8 DAYS AGO',
    },
  },
];
